--- 
master_template: cf_template.yaml
bucketname: takshika-cftemplate
subdirectory: CICD
stack_name: "{{ stack_prefix }}"
VAULT_DIRECTORY: s3://takshika-cftemplate/
ansible_ssh_pass: test
region: us-east-1d
